---
name: test

on:
  push:
    paths:
      - 'src/*'
      - '*.nimble'
      - '.github/*'
  pull_request:
    paths:
      - 'src/*'
      - '*.nimble'
      - '.github/*'

env:
  NIM_VERSION: '1.4.8'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.NIM_VERSION }}
      - run: nimble build -Y
      - run: nimble jsBuild
      - run: nimble test -Y
